### ISSUE TITLE
Create a showcase app/window

### ISSUE THREAD

**Issue by oclero** [oclero/qlementine#34]
- [x] Create a showcase app with a dummy window, to show how Qlementine looks.
- [ ] Make some screenshots and use them in README.md

**Comment by MartinBriza** [comment]
Hi, your project seriously lacks pictures! A few years ago I wrote this application to showcase a style I was writing at the time and it mimicked the showcase GTK3 had then. I specifically picked up a commit where all of the code in the showcase was written by only me and if you want to use it, I give you permission to do so under whatever license you decide to use, if you do so. Have a nice day!

https://github.com/FedoraQt/adwaita-qt/tree/cd7b927ba5e71645a3bbf45472cad13abfd15ad6/src/example

**Comment by oclero** [comment]
@MartinBriza Oh thanks! 😀 I was planning to make this showcase window this week, so I'll have a look at your code!

**Comment by oclero** [comment]
@MartinBriza Also, are you OK if I re-use most of your CI script? (Building on Linux in Qt5 AND Qt6, building on Windows, and I'll add building on MacOS)

**Comment by MartinBriza** [comment]
That CI script is not written by me, I haven't contributed to that project in years (again, which is why I'm linking a specific commit) but from the licensing perspective, I don't think it's an issue. You can check the CI script here though https://github.com/LithApp/Lith and do whatever you want with it... it's pretty messy though but it works on all Qt target platforms (except Android now because of QCoro).

**Comment by MartinBriza** [comment]
Look at the `wasm` part especially, that's how https://lith.app/Lith is built, would be a nice way to showcase your project ;)

**Comment by oclero** [comment]
@hirseboy I was working on creating an icon library. It's mostly done, so I'll be able soon to make a showcase app.

**Comment by hirseboy** [comment]
@oclero ok, sounds great! :)
